namespace Lunar.Input
{
    public enum Button
    {
        A,  B,  X,  Y,
        START,  BACK,  LEFTSHOULDER,  RIGHTSHOULDER, 
        LEFTSTICK,  RIGHTSTICK,  BUTTON_10, BUTTON_11,
        BUTTON_12, BUTTON_13, BUTTON_14, BUTTON_15,

        DPAD_LEFT, DPAD_RIGHT, DPAD_UP, DPAD_DOWN,
    }

    public enum Axis
    {
        RIGHTX, RIGHTY, LEFTX, 
        LEFTY, TRIGGERLEFT, TRIGGERRIGHT,
    }

    public enum Key
    {
        BUTTON_0,  BUTTON_1,  BUTTON_2,  BUTTON_3,
        BUTTON_4,  BUTTON_5,  BUTTON_6,  BUTTON_7,
        BUTTON_8,  BUTTON_9,  BUTTON_10, BUTTON_11,
        BUTTON_12, BUTTON_13, BUTTON_14, BUTTON_15,
        BUTTON_16, BUTTON_17, BUTTON_18, BUTTON_19,
        BUTTON_20, BUTTON_21, BUTTON_22, BUTTON_23,
        BUTTON_24, BUTTON_25, BUTTON_26, BUTTON_27,
        BUTTON_28, BUTTON_29, BUTTON_30, BUTTON_31,
    }
}
